/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fxErc721ChildTunnelSol from "./FxERC721ChildTunnel.sol";
export type { fxErc721ChildTunnelSol };
import type * as fxErc721RootTunnelSol from "./FxERC721RootTunnel.sol";
export type { fxErc721RootTunnelSol };
