/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FxRoot } from "./FxRoot";
export type { IFxStateSender } from "./IFxStateSender";
export type { IStateSender } from "./IStateSender";
