/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FxStateChildTunnel } from "./FxStateChildTunnel";
export type { FxStateRootTunnel } from "./FxStateRootTunnel";
